concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: 1.8.0
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          show-progress: false
      - name: Apply terraform fmt and find unformatted files
        run: |
          bash -ex ./.github/terraform-fmt.sh
    timeout-minutes: 10
name: terraform-checks
on:
  pull_request:
    paths:
      - '**.tf'
